name: 'Docker Action - HW'
description: 'Basic HW with Docker'
inputs:
  who-to-greet:
    description: 'Who to greet'
    default: 'world'
outputs:
  time:
    description: 'Current time'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
