name: GitHub Actions Demo
run-name: Test workflow ${{ github.run_number }}

defaults:
  run:
    shell: pwsh

on:
  push:
    branches: [main]
    paths-ignore: [.github/**] 
  pull_request:
    branches: [main]
  schedule:
    - cron: '15 6 * * SUN'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the env to deploy to'
        type: environment
        required: true
    
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Event name:${{ github.event_name }}"
          echo "Branch name:${{ github.ref }} / Repo name:${{ github.repository }}"
      - uses: actions/checkout@v4.0.0
      - name: Repository file list
        run: |
          echo "The repo has these files:"
          tree

  Test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: Build
    environment: Test
    steps:
      - run: echo "🧪 Testing..."

  Load-Test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: Build
    environment: Load-Test
    steps:
      - run: |
          echo "🧪 Testing..."
          sleep 15

  Production:
    runs-on: ubuntu-latest
    needs: [Test, Load-Test]
    environment:
      name: Required reviewer
      url: https://writeabout.net
    if: github.event.inputs.environment == 'Required reviewer'
    steps:
      - run: |
          echo "Step 1..."
          sleep 10
      - run: |
          echo "Step 2..."
          sleep 10
      - run: |
          echo "Step 3..."
          sleep 10
      - run: |
          echo "🚀 Step 4..."
          sleep 10
      - run: |
          echo "Step 5..."
          sleep 10
